apollo:
  meta: http://120.77.40.230:8080
app:
  id: why


server:
  servlet:
    context-path: /why
  port: 8001
mybatis:
  mapper-locations: classpath:mapper/*.xml


#spring:
#  redis:
#    database: 0
#    host: 116.63.132.115
#    port: 6379
#    password:
#    pool:
#      max-active: 200
#      max-wait: -1
#      max-idle: 10
#      min-idle: 0
#    timeout: 1000